# Generated by Django 4.1 on 2022-10-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0006_portada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portada',
        ),
    ]
