# Generated by Django 4.1 on 2022-10-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0012_remove_libros_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(default='/portadas/default_cover.jpg', upload_to='portadas'),
            preserve_default=False,
        ),
    ]
