# Generated by Django 4.1 on 2022-10-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0019_libros_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='sumario',
        ),
    ]
