# Generated by Django 4.1 on 2022-10-14 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0020_remove_libros_sumario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='libros',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
