# Generated by Django 4.1 on 2022-10-15 22:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0021_libros_post_date_libros_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
