# Generated by Django 4.1 on 2022-10-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0022_libros_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(upload_to='avatares'),
        ),
    ]
